function discontinuousdata32 = import_discontinous_monkey_VR(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DISCONTINUOUSDATA32 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  DISCONTINUOUSDATA32 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  discontinuousdata32 = importfile("/Volumes/server3/Projects/Firefly-moving_firefly/Data/Pilot2-Human/jp/different_on_times/lat_move_noFB/001/discontinuous_data_32.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Oct-2020 18:35:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
Nvariables = 58;
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
%opts.VariableNames = ["n", "max_v", "max_w", "ffv", "onDuration", "density", "PosX0", "PosY0", "PosZ0", "RotX0", "RotY0", "RotZ0", "RotW0", "ffX", "ffY", "ffZ", "pCheckX", "pCheckY", "pCheckZ", "rCheckX", "rCheckY", "rCheckZ", "rCheckW", "distToFF", "rewarded", "timeout", "juiceDuration", "beginTime", "checkTime", "rewardTime", "endTime", "waitTime", "ITI"];
opts.VariableNames = ["n", "max_v", "max_w", "ffv", "onDuration", "density", "PosX0", "PosY0", "PosZ0", "RotX0", "RotY0", "RotZ0", "RotW0", "ffX", "ffY", "ffZ", "pCheckX", "pCheckY", "pCheckZ", "rCheckX", "rCheckY", "rCheckZ", "rCheckW", "distToFF", "rewarded", "timeout", "juiceDuration", "beginTime", "checkTime", "rewardTime", "endTime", "waitTime", "ITI","ptbJoyVelMin","ptbJoyVelMax","ptbJoyVelStartRange","ptbJoyVelStart","ptbJoyVelMu","ptbJoyVelSigma","ptbJoyVelGain","ptbJoyVelEnd","ptbJoyVelLen","ptbJoyVelValue","ptbJoyRotMin","ptbJoyRotMax","ptbJoyRotStartRange","ptbJoyRotStart","ptbJoyRotMu","ptbJoyRotSigma","ptbJoyRotGain","ptbJoyRotEnd","ptbJoyRotLen","ptbJoyRotValue","ptbJoyFlag","ptbJoyFlagTrial","ptbJoyRatio","ptbJoyOn","ptbJoyEnableTime"];
opts.VariableTypes = repmat({"double"},1,Nvariables); 
% count('ptbJoyVelMin,ptbJoyVelMax,ptbJoyVelStartRange,ptbJoyVelStart,ptbJoyVelMu,ptbJoyVelSigma,ptbJoyVelGain,ptbJoyVelEnd,ptbJoyVelLen,ptbJoyVelValue,ptbJoyRotMin,ptbJoyRotMax,ptbJoyRotStartRange,ptbJoyRotStart,ptbJoyRotMu,ptbJoyRotSigma,ptbJoyRotGain,ptbJoyRotEnd,ptbJoyRotLen,ptbJoyRotValue,ptbJoyFlag,ptbJoyFlagTrial,ptbJoyRatio,ptbJoyOn,ptbJoyEnableTime,',',')

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
discontinuousdata32 = readtable(filename, opts);

%% Convert to output type
discontinuousdata32 = table2array(discontinuousdata32);
end