  function continuousdata = import_continous_monkey_VR(filename)
%IMPORTFILE Import data from a text file
%  CONTINUOUSDATA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CONTINUOUSDATA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  continuousdata = importfile("/Volumes/server/Projects/Firefly-moving_firefly/Data/Pilot2-Human/Janna/09262020/config_lat_move_noFB/continuous_data_7087.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Sep-2020 20:07:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
Nvariables = 35;
opts = delimitedTextImportOptions("NumVariables", Nvariables);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TrialNum", "TrialTime", "Phase", "OnOff", "PosX", "PosY", "PosZ", "RotX", "RotY", "RotZ", "RotW", "LinearVelocty", "AngularVelocity", "FFX", "FFY", "FFZ", "FFV", "EyeContext", "Confidence", "GazeX", "GazeY", "GazeZ", "GazeDistance", "RCenterX", "RCenterY", "RCenterZ", "LCenterX", "LCenterY", "LCenterZ", "RNormalX", "RNormalY", "RNormalZ", "LNormalX", "LNormalY", "LNormalZ"];
opts.VariableTypes = repmat({"double"},1,Nvariables); 

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
continuousdata = readtable(filename, opts);

%% Convert to output type
continuousdata = table2array(continuousdata);

  end